import CustomNavbar from "../components/CustomNavbar";
const About =()=>{
    return(
        
        <div className="container">
            <header>
               <CustomNavbar></CustomNavbar>
            </header>
            <main>
                <section>
                    <div>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean accumsan quam et ex eleifend, a iaculis mauris convallis. Nunc a mattis ligula. Sed dictum pharetra massa, vel cursus quam vulputate id. Proin rutrum varius dolor ac condimentum. Phasellus ac pharetra dui. Ut turpis lorem, fermentum at odio et, cursus molestie ex. Nulla ultricies tellus et tellus luctus dapibus finibus suscipit risus. Phasellus vel ante id justo pharetra fringilla. Fusce sed sapien libero. Etiam id massa ut urna porttitor elementum.

Nam faucibus lorem justo. Curabitur aliquam urna finibus quam fringilla aliquet. Vestibulum eu nisi eros. Vestibulum efficitur urna nisl, vel rutrum nibh gravida nec. Praesent lectus lorem, tincidunt a lacinia sit amet, gravida sed nulla. Aliquam in gravida felis. Nulla nec quam erat. Fusce risus lorem, condimentum sit amet est sed, dignissim sollicitudin risus. Ut pellentesque suscipit ipsum malesuada tempor. Nulla molestie sem vitae mi euismod, quis lobortis velit volutpat. Suspendisse in odio quis diam rutrum elementum. Cras et tincidunt ante, eget consequat elit. Praesent feugiat diam in orci lacinia, eu tristique quam egestas. Sed efficitur ante eu eros convallis viverra. Duis neque ligula, iaculis eget risus in, pretium porta dui. Donec eu lobortis ligula, sed malesuada dolor.

Pellentesque tincidunt blandit enim rutrum congue. Fusce volutpat justo ut posuere dapibus. Aliquam eget tristique augue. Donec neque purus, tincidunt et tempor id, egestas ut lacus. Vestibulum eu feugiat elit. Nam iaculis pretium maximus. Pellentesque eu dui vel tortor cursus ultricies. In finibus erat in mi placerat, ac placerat sem fringilla. Pellentesque vel dolor euismod lacus pharetra porttitor. Aliquam finibus, neque at pellentesque molestie, dolor nisl varius lorem, nec gravida nulla erat eu dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam vulputate mattis efficitur.

Duis et leo quis ex aliquam hendrerit. Fusce eu lectus ac eros faucibus suscipit ac sit amet sem. Praesent mollis elit vel libero aliquet, vel ornare ipsum vehicula. Aliquam cursus ornare arcu ut molestie. Phasellus condimentum ut lorem non ornare. Phasellus ac convallis magna. Mauris ac lacus sollicitudin, fermentum libero eu, fringilla ante. Cras sollicitudin bibendum erat non condimentum. Donec sapien odio, pulvinar in justo ut, rutrum consequat velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam quis convallis metus. Duis vitae rutrum nisi, eget vehicula erat. Sed ut ligula consequat justo elementum facilisis in eu nibh.

Suspendisse aliquet orci a est condimentum finibus. Praesent ac sollicitudin enim. Ut eget congue massa, et aliquet felis. Etiam quis consectetur mauris. Etiam aliquam laoreet tincidunt. Pellentesque auctor eu felis eget placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur pretium semper gravida. Aliquam in mi tincidunt nisl facilisis pretium in at purus. Quisque id ultricies nunc.

Nunc non commodo lorem. Nam nec lectus mattis, aliquet massa nec, tincidunt nisl. Maecenas pulvinar venenatis odio. Curabitur et euismod tortor. Phasellus laoreet erat a pharetra viverra. Maecenas posuere enim quis consectetur tristique. Integer in sodales quam. Integer rutrum, elit eu gravida viverra, metus sapien varius lorem, et pretium augue ipsum in ex. Curabitur a orci quam. In facilisis arcu ut leo faucibus, a ultrices nulla fringilla. Sed gravida leo at ultricies ultrices. Etiam in quam augue. Fusce non lacus a enim porta egestas. Donec facilisis lobortis quam eu volutpat. Nunc tempus, dolor at blandit interdum, arcu neque vestibulum eros, vitae scelerisque orci libero nec nunc.

Phasellus augue nisi, pellentesque nec tincidunt quis, maximus sit amet massa. Morbi tincidunt, ipsum eu lobortis laoreet, magna lorem porttitor augue, at suscipit velit nibh eu dui. Morbi et lectus efficitur, tempus ante non, lobortis neque. Vivamus at cursus justo. Fusce scelerisque libero vel turpis mattis, eget pulvinar nulla convallis. Curabitur pharetra lobortis eros eu volutpat. In a purus ut nisl maximus consequat volutpat cursus lorem. Curabitur consequat, orci in varius auctor, augue augue semper lorem, et dapibus mi mi sit amet tortor. Nam tincidunt purus vel lacinia iaculis. In fringilla hendrerit hendrerit. Proin accumsan pharetra eros, sed blandit nibh placerat eget. Curabitur tincidunt mi at dui hendrerit, vel vulputate nisl vestibulum.

Pellentesque convallis ornare mauris a vulputate. Phasellus sit amet cursus quam. Etiam ac odio rutrum, venenatis dolor placerat, mollis urna. Cras ornare erat eu nulla varius rhoncus. Sed mattis est eu nunc gravida, quis egestas lectus mollis. Ut pellentesque ex vitae mauris molestie vestibulum. Fusce faucibus pulvinar mauris sit amet accumsan.

Nunc eleifend fermentum convallis. Donec tristique tempus tempus. Nam euismod augue fermentum lorem porttitor, sit amet lobortis nibh egestas. Vivamus consectetur mollis odio, sit amet ullamcorper augue molestie id. Fusce tempor volutpat lorem, id feugiat ligula vehicula id. Nullam convallis elementum arcu non ultricies. Aenean a leo dignissim, consequat neque non, condimentum magna. Curabitur at turpis id dui lacinia lobortis non vitae enim. Nulla auctor orci eget laoreet luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus at metus a urna bibendum finibus vel quis ligula.

Praesent ex nibh, pharetra quis tempus id, facilisis eleifend purus. Integer vel viverra libero. Nam sed vulputate dolor, at elementum augue. Vivamus scelerisque sem quis rutrum ultrices. Nulla a convallis sapien. Ut hendrerit accumsan magna eu sodales. Vestibulum semper eros viverra erat ultrices ornare. Vestibulum tincidunt faucibus luctus. Nam in pellentesque mi. Phasellus non malesuada felis.

Aenean consequat elit nec mauris ultrices porta. Nam tincidunt lorem eu justo cursus imperdiet. Aenean interdum eget nulla nec luctus. Nunc rhoncus, massa vel tempus ullamcorper, eros augue feugiat velit, vel vestibulum massa ex nec erat. Cras vitae lobortis quam. Nam at venenatis eros. Phasellus pharetra finibus velit, non varius leo accumsan non. Phasellus quis consequat tellus, eu hendrerit velit. Vestibulum eu purus in eros dapibus rutrum eu ut leo. Integer dapibus nisl eu ipsum tincidunt porta. Donec a vehicula felis, vel aliquam lectus. Mauris mi massa, bibendum ut sagittis et, posuere vitae purus. Vivamus lacinia feugiat dui, ut efficitur lectus lacinia at. Nam at erat eu eros auctor tristique.

Donec in consequat ex. Aenean euismod sapien a dolor molestie, et auctor sem dictum. Praesent gravida libero quam, nec luctus urna facilisis et. Nam ex lacus, lobortis posuere massa finibus, mollis faucibus velit. Quisque ut cursus urna. Etiam fermentum urna eget dui porta, et rutrum elit sodales. Fusce luctus mauris rhoncus elit viverra lobortis. Maecenas iaculis, arcu et luctus pellentesque, tortor velit rutrum arcu, nec tincidunt mauris ante id arcu. Nullam vestibulum eget nisi faucibus consequat. Cras faucibus congue ipsum, auctor vulputate sem accumsan at.

Proin tincidunt risus ac lobortis posuere. Phasellus nec risus nec sem maximus ornare ac sed sem. Etiam molestie auctor ante, a pellentesque odio pellentesque sed. Curabitur condimentum quis nisi a ultricies. Maecenas molestie odio vitae faucibus bibendum. Morbi scelerisque odio eu accumsan ultricies. Sed non nulla nulla. Donec dolor mauris, gravida vitae consectetur a, iaculis sit amet nunc. Etiam quis dignissim sapien, quis pulvinar sem.

Cras vulputate neque ac mauris malesuada consequat. Duis hendrerit laoreet ex vitae fringilla. Phasellus efficitur eu nisi ut bibendum. Cras ut enim felis. Sed vel risus facilisis, placerat lacus in, volutpat ex. Suspendisse sed maximus nisi. Sed convallis dolor sed finibus ullamcorper. Integer scelerisque vestibulum consequat. In euismod ornare ligula vitae sagittis. Integer eget justo tellus. Duis aliquam lectus quis justo rutrum, ut facilisis dui scelerisque. Suspendisse congue at purus id iaculis. Aliquam placerat libero nec facilisis mollis. Curabitur eget dolor ut nibh condimentum dapibus. Suspendisse neque dui, tempor ac quam ut, rhoncus sollicitudin arcu.

Quisque lobortis ornare ornare. Aenean accumsan blandit laoreet. Nullam id elementum tortor. Maecenas leo justo, aliquet nec facilisis in, consectetur at ipsum. Fusce vel erat auctor nibh ornare blandit at fringilla nibh. Donec ornare neque justo, nec iaculis turpis vehicula vitae. Nam sodales maximus magna, vel pulvinar sapien rhoncus consectetur. Fusce vel velit vitae massa maximus vehicula. Duis mollis sapien id augue accumsan, vel finibus sapien vestibulum. Morbi quis massa efficitur, feugiat mauris sed, condimentum nibh. Ut lobortis sem mauris, eget pharetra nunc rhoncus sit amet. Etiam viverra nibh sed eleifend fringilla. Fusce non diam ut mauris interdum porta. Sed ultricies, eros varius suscipit consequat, risus ipsum accumsan tortor, nec pharetra sem metus eu leo.

Maecenas maximus accumsan eros vel tincidunt. Maecenas luctus odio augue, sed dignissim libero viverra in. Cras ante nunc, interdum non diam vel, semper dictum tortor. Maecenas porta efficitur dui, sed ullamcorper mauris laoreet ac. Sed at vehicula ante. Nullam vitae vehicula libero. Donec sit amet metus porttitor, volutpat nibh eget, ornare diam. Donec id sodales urna, quis faucibus ipsum. In hac habitasse platea dictumst. Morbi ac enim non dolor commodo blandit vel non sapien. Integer eu fringilla diam, eget lacinia ipsum. Nunc commodo, libero sit amet fringilla venenatis, lectus neque faucibus quam, at ullamcorper erat dui in ante.

Maecenas vehicula nibh quis nisl luctus, ac scelerisque ligula iaculis. Pellentesque varius justo id urna facilisis egestas. Phasellus varius, massa vitae malesuada dapibus, lectus diam tincidunt quam, sed hendrerit turpis tortor at felis. Donec fermentum vestibulum dui, ac egestas dui placerat malesuada. Suspendisse eget bibendum nulla. Proin consequat et diam et lobortis. Duis vitae malesuada metus. Cras porta mauris eu leo molestie, eget fermentum nisl tempor. Sed scelerisque fermentum interdum. Nam id erat in arcu elementum fringilla eget quis metus. In imperdiet, est et ornare sollicitudin, est mauris tempus neque, eget hendrerit diam orci quis ex. Vestibulum placerat sit amet ligula ut interdum. Duis vestibulum neque vitae urna finibus, eu placerat sapien malesuada. Ut vehicula eu leo nec tincidunt. Ut nec ex sagittis, dignissim diam quis, scelerisque mi.

Cras finibus urna ut auctor cursus. Donec consequat blandit tellus nec tempor. Cras id cursus eros. Phasellus nec sodales est. Donec mollis quam quam, at ultrices eros volutpat sit amet. Nunc imperdiet sollicitudin augue vel maximus. Nullam at fringilla leo. Pellentesque consequat sed massa sed faucibus. Ut non diam leo. Cras sit amet sem nec massa facilisis placerat. Nulla vulputate consequat aliquam. Ut fringilla urna eget lacus finibus euismod. Suspendisse pulvinar lorem pretium tellus malesuada, sit amet laoreet nulla gravida. Proin id dui suscipit metus vehicula euismod.

Aliquam semper auctor mauris et tempus. Aenean pretium vel massa sed ultricies. Curabitur fringilla varius nibh, sit amet placerat orci ultrices in. Donec vel orci ut odio dapibus accumsan vitae et sem. Suspendisse ultrices tempor cursus. Etiam semper lectus non rhoncus tempor. Aenean sodales rhoncus velit, in scelerisque metus tristique mollis. Maecenas ornare ipsum ornare metus elementum elementum. Nam eu efficitur arcu. Donec felis nunc, condimentum ut dignissim nec, blandit non eros. Proin ullamcorper ultrices faucibus. Nunc lobortis fermentum lorem vel volutpat.

Praesent posuere dui risus, eu lacinia justo tristique non. Nulla non lacus in arcu pretium aliquet. Maecenas tempor, tellus quis dapibus vestibulum, mauris nisl pulvinar sapien, sit amet venenatis ligula velit vitae lorem. Aliquam eget dolor urna. Donec vulputate est pellentesque hendrerit pellentesque. Aenean vel ultricies felis. Pellentesque consequat eu risus sed egestas. Vivamus enim lectus, faucibus non elementum eget, convallis sed quam. Suspendisse pellentesque posuere sodales
                    </div>
                </section>
            </main>
        </div>
    )
}
export default About